spring:
  application:
    name: OneAndZeroBest
  datasource:
    url: jdbc:mysql://localhost:3306/siumechu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
   email:
    verification:
      subject: 이메일 인증
      text: 귀하의 인증 코드는 %s 입니다.
      expiry: 3

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000

server:
  port: 8080
