spring:
  application:
    name: OneAndZeroBest
  datasource:
    url: jdbc:mysql://localhost:3306/siumechu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:
    key: e36f112d-c6f2-466f-aad8-14dcdc16360b
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000

server:
  port: 8080
